### ISSUE TITLE
how to edit the config file 

### ISSUE THREAD

**Issue by hewei9** [daeunSong/glURDF#5]
Hi! Thanks for the great work！
I am trying to access my own robot urdf file and add some actions，and I wonder how to generate config file for different robot actions.Hope to recieve ur reply.Thanks a lot！

**Comment by daeunSong** [comment]
Hello,

In order to try it out with your own robo urdf, you need to change the file paths in the demo examples. 
For example, with the fetch_say_hi example, please change the file paths in [here](https://github.com/EwhaGlab/glURDF/blob/bab75cb2c133e7624682c2fd4c0bf1ec4e9dd009/src/demo_fetch_say_hi.cpp#L45-L48).

Regarding generating the configuration (action) file, it's a sequential arrangement of all joint values according to their time stamps.

e.g.
> time_0_joint_0
> time_0_joint_1
> ...
> time_0_joint_n
> time_1_joint_0
> ...
> time_1_joint_n
> time_t_joint_0
> ...
> time_t_joint_n


Hope this helps.

Thanks!
